# Generated by Django 5.2.5 on 2025-08-14 02:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, help_text='API key for authentication', unique=True)),
                ('daily_query_limit', models.IntegerField(default=1000, help_text='Maximum number of queries allowed per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('organization', models.CharField(blank=True, help_text="User's organization or institution", max_length=255)),
                ('role', models.CharField(choices=[('researcher', 'Researcher'), ('student', 'Student'), ('admin', 'Administrator'), ('public', 'Public User')], default='researcher', max_length=50)),
                ('last_active', models.DateTimeField(blank=True, help_text='Last API activity timestamp', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
