# Generated by Django 5.2.5 on 2025-08-14 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='Original text input for analysis')),
                ('result', models.CharField(help_text='Analysis result/category', max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence score (0.0 to 1.0)')),
                ('explanation_json', models.JSONField(default=dict, help_text='Detailed explanation and factors')),
                ('latency_ms', models.PositiveIntegerField(help_text='Processing time in milliseconds')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When analysis was performed')),
            ],
            options={
                'db_table': 'analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analysis_created_43d70b_idx'), models.Index(fields=['result'], name='analysis_result_dde311_idx'), models.Index(fields=['confidence'], name='analysis_confide_5adf58_idx')],
            },
        ),
    ]
